import type { MarketType } from '@/lib/display/displayPolicy';

export type DisplayCard = {
  id: string;
  assetKey: string;
  symbol: string;
  name: string;
  market: MarketType;
  marketLabel: string;
  theme?: string | null;
  cardType: string;
  title: string;
  primaryReason: string;
  secondaryReason?: string | null;
  price?: number | null;
  changePct?: number | null;
  volume?: number | null;
  amount?: number | null;
  labels: string[];
  dataBasisLabel: string;
  source: string;
  updatedAt?: string | null;
  tvSymbol?: string | null;
  coingeckoId?: string | null;
  binanceSymbol?: string | null;
  upbitMarket?: string | null;
  chartSetupType?: string | null;
  technicalSnapshot?: {
    timeAdjustedVolumeRatio?: number;
    timeAdjustedAmountRatio?: number;
    volumeRatio20?: number;
    amountRatio20?: number;
    amountRankPct?: number;
    amountRankJump?: number;
    distanceToPrevHighPct?: number;
    breakoutLookbackDays?: number;
    boxRangePct?: number;
    boxBreakout?: boolean;
    closeToHighPct?: number;
    intradayRangePct?: number;
    volatilityRank20?: number;
    ma5Slope?: number;
    ma20Slope?: number;
    isAboveMa5?: boolean;
    isAboveVwap?: boolean;
    gapPct?: number;
    morningHighBreakout?: boolean;
    vwapReclaim?: boolean;
    afternoonReacceleration?: boolean;
    pullbackDays?: number;
    pullbackDepthPct?: number;
    previousDayChangePct?: number;
    previousDayVolumeRatio20?: number;
    afterHoursChangePct?: number;
    marketRelativeStrengthPct?: number;
  };
  themeSnapshot?: {
    themeBreadthUpCount?: number;
    themeTotalCount?: number;
    themeAvgChangePct?: number;
    themeAmountRatio?: number;
    themeVolumeRatio?: number;
    themeLeaderSymbol?: string;
    isThemeLeader?: boolean;
    themeRole?: 'leader' | 'second' | 'follower' | 'overheated' | 'laggard' | 'none';
  };
  riskSnapshot?: {
    isInvestmentWarning?: boolean;
    isLowLiquidity?: boolean;
    upperWickPct?: number;
    gapPct?: number;
    overheatScore?: number;
  };
  isWidget?: boolean;
  isMock?: boolean;
};

export type DataEnvelope<T> = {
  ok: true;
  mode: 'live' | 'mock';
  source: string;
  basis: string;
  updatedAt: string;
  items: T[];
  message?: string;
  missing?: string[];
  fallback?: boolean;
};
